site_name: Fine-Tuning SAM Model

nav:
  - Overview: index.md
  - Helpers: helpers.md
  - Configuration: config.md
  - Plots: plots.md
  - Preprocess Images: preprocess_image.md
  - Train: main.md
  - 日本語: japanese.md

theme: readthedocs


